spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahiruzuy/msa_study_config
          searchLocations: classpath:/config

test:
  profile: i'm dev
  said:
    first: Hello
    second: Config Server