spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahiruzuy/msa_study_config/
          search-paths:
            - "config-server-properties/{application}/{profile}"