eureka:
  instance:
    hostname: eureka-server2
    appname: eureka-app
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server1:8761

management:
  endpoints:
    web:
      exposure:
        include: '*'