eureka:
  instance:
    hostname: eureka-server1
    appname: eureka-app
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server2:8762/eureka
  server:
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: '*'