eureka:
  instance:
    hostname: eureka-server1
    appname: eureka-app
#    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'