eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      perferIpAddress: true

logging:
  level:
    org.springframework.web: DEBUG