eureka:
  client:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    healthcheck:
      enabled:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    instance:
      perferIpAddress: true

logging:
  level:
    org.springframework.web: DEBUG